# stages:
#   clean_data:
#     cmd: python src/prepare.py --input data/raw/MachineLearningRating_v3.zip --output data/processed/cleaned_insurance_data.csv
#     deps:
#       - data/raw/MachineLearningRating_v3.zip
#       - src/prepare.py
#     outs:
#       - data/processed/cleaned_insurance_data.csv

stages:
  prepare:
    cmd: python src/prepare.py --config params.yaml
    deps:
      - src/prepare.py
      - data/raw/MachineLearningRating_v3.zip
    params:
      - prepare.seed
      - prepare.split_ratio
    outs:
      - data/processed/cleaned_insurance_data.csv
      - data/processed/test.csv

  train:
    cmd: python src/modeling.py --config params.yaml
    deps:
      - src/modeling.py
      - data/processed/cleaned_insurance_data.csv
    params:
      - train.epochs
      - train.lr
      - train.batch_size
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/modeling.py --config params.yaml
    deps:
      - src/modeling.py
      - data/processed/cleaned_insurance_data.csv
      - models/model.pkl
    metrics:
      - evaluation/metrics.json:
          cache: false
    plots:
      - evaluation/plots/confusion_matrix.json:
          cache: false
          x: actual
          y: predicted